#!/usr/bin/env node

/**
* Module dependencies.
*/
var child_process = require('child_process'),
    path = require('path'),
    program = require('commander'),
    tools = require('./tools');

var exec = child_process.exec,
    conf = {
        port: 9090
    },
    _port = '9090';

function setPort( val ){
    conf.port = val;
}

function startServer(){
    var root = path.resolve('./');
    var port = conf.port;
    var jarPath = path.resolve(__dirname + '/libs/server.jar');

    var startSerCommond = 'java -jar  ' + jarPath + ' --base ./ --root ' + root + ' --port ' + port;
    console.log('* Server is starting , port is ' + port);

    var server = exec(startSerCommond, function( err, stdout, stderr ){
        if(err) 
            console.log('* 服务器启动失败！', err);
            throw err;
        console.log('* Congratulation, 服务器启动成功!');
        console.log('* PID: ', server.pid)
    })

    setTimeout(function() {
        console.log('* PID: ', server.pid);
    }, 500);
}

program
    .version('0.0.1')
    .usage('[options] <file ...>')
    .option('-s, --server', '启动web服务器')
    .option('-p, --port <num>', '指定服务启动端口', setPort)
    .parse(process.argv);

// setConfig();
startServer();
